image: node

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
            - yarn.lock
    script:
        - yarn --prod
        - yarn build
        # - rm -Rf public
        # - mv build public
    publish: build
    artifacts:
        paths:
            - build # public
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # only:
    #     - master
