image: node:18-alpine

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
            - yarn.lock
    script:
        - yarn --prod
        - yarn build
    publish: build
    artifacts:
        paths:
            - build
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
