image: node

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
            - yarn.lock
    script:
        - yarn # npm install
        - yarn build # npm run build
        # - rm -Rf public
        # - mv build public
    publish: build
    artifacts:
        paths:
            - build
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # only:
    #     - master
