name: prueba_react
services:
    juegos_react_dev_bun:
        container_name: juegos_react_dev_bun
        # image: oven/bun:slim
        image: oven/bun:alpine
        working_dir: /app
        command:
            - /bin/sh
            - -c
            - |
                bun install
                bun run dev
        ports:
            - 4000:4000
        tty: true
        volumes:
            - ./:/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        # restart: on-failure
        # restart: unless-stopped
