version: "3"
services:
    juegos_react_compiler:
        container_name: juegos_react_compiler
        image: node:18-alpine
        working_dir: /app
        command:
            - /bin/sh
            - -c
            - |
                yarn --prod
                yarn build
                rm -Rf buildhtml/* > /dev/null
                rm -Rf buildhtml/.* > /dev/null
                mv build/.* buildhtml
                mv build/* buildhtml
        volumes:
            - ./:/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    juegos_react_server:
        container_name: juegos_react_server
        image: nginx:stable-alpine
        volumes:
            - ./buildhtml:/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 80:80
            - 8080:80
        restart: unless-stopped
        depends_on:
            - juegos_react_compiler
