name: juegos_react

services:

    juegos_react_builder:
        container_name: juegos_react_builder
        image: node:20-alpine
        tty: true
        working_dir: /app
        command:
            - /bin/sh
            - -c
            - |
                yarn --prod
                yarn build
        volumes:
            - ./:/app
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    juegos_react_web:
        container_name: juegos_react_web
        image: juegos_react_nginx
        build: 
            context: ./
            dockerfile: ./dockerfileNginx
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 80:80
        # restart: unless-stopped
