name: juegos_react

services:

    juegos_react:
        container_name: juegos_react
        image: juegos_react_imagen
        build: 
            context: ./
            dockerfile: ./Dockerfile
        tty: true
        command:
            - /bin/sh
            - -c
            - |
                mv /tmp/yarn.lock /nodebuild/yarn.lock -f
                mv /tmp/node_modules /nodebuild/node_modules -f
                nginx -g 'daemon off;'
        volumes:
            - ./nodebuild:/nodebuild
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 80:80
        # restart: unless-stopped
